(function(global){'use strict';
const KEY='compounder.story.sees.v1',labels={yes:'是',maybe:'不一定',unsure:'我还不确定'};
function normalize(raw){const x=raw&&typeof raw==='object'?raw:{};return {choice:Object.hasOwn(labels,x.choice)?x.choice:null,draft:typeof x.draft==='string'?x.draft.slice(0,4000):'',entries:Array.isArray(x.entries)?x.entries.filter(e=>e&&typeof e.text==='string'&&typeof e.date==='string').map(e=>({text:e.text.slice(0,4000),date:e.date,choice:Object.hasOwn(labels,e.choice)?e.choice:null})):[]};}
function addEntry(state,text,date){const clean=text.trim();if(!clean)return false;if(state.entries[0]?.text===clean){state.draft=clean;return true;}state.entries.unshift({text:clean,date,choice:state.choice});state.draft=clean;return true;}
function exportRecord(s){return '# 喜诗糖果：我的判断记录\n\n来源：巴菲特 2007 年致股东信\nhttps://www.berkshirehathaway.com/letters/2007ltr.pdf\n\n问题：增长需要不断购买昂贵设备，是否意味着没有护城河？\n当前选择：'+(labels[s.choice]||'未选择')+'\n\n'+s.entries.map(e=>'## '+e.date+'\n\n'+e.text+'\n\n当时选择：'+(labels[e.choice]||'未选择')).join('\n\n')+(s.draft.trim()&&s.draft.trim()!==s.entries[0]?.text?'\n\n## 未提交的草稿\n\n'+s.draft:'');}
async function* events(body){const reader=body.getReader(),decoder=new TextDecoder();let pending='';try{while(true){const {value,done}=await reader.read();pending+=done?decoder.decode():decoder.decode(value,{stream:true});let end;while((end=pending.indexOf('\n'))>=0){const line=pending.slice(0,end).trimEnd();pending=pending.slice(end+1);if(line.startsWith('data: '))yield JSON.parse(line.slice(6));}if(done){if(pending.startsWith('data: '))yield JSON.parse(pending.slice(6));break;}}}finally{reader.releaseLock();}}
if(typeof module!=='undefined'&&module.exports)module.exports={normalize,addEntry,exportRecord,events};if(!global.document)return;
const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};let state;try{state=normalize(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){state=normalize({});}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){$('note-status').textContent='此浏览器无法保存，请导出记录保留本次理解。';return false;}}
function renderEntries(){const root=$('past-notes');root.replaceChildren();for(const [i,e] of state.entries.entries()){const article=el('article');article.className='past-note';const date=new Date(e.date);article.append(el('time',Number.isNaN(date.getTime())?'已保存的理解':date.toLocaleString('zh-CN')),el('p',e.text));if(e.choice)article.append(el('small','当时的选择：'+labels[e.choice]));if(i===0){const title=el('h3','上次留下的理解');article.prepend(title);}root.append(article);}}
function choice(){document.querySelectorAll('[data-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.choice===state.choice)));const root=$('choice-feedback');root.hidden=!state.choice;if(!state.choice)return;root.replaceChildren();root.append(el('strong',state.choice==='maybe'?'这与案例中的证据一致。':state.choice==='unsure'?'可以先把两个问题分开看。':'FlightSafety 的例子，值得再看一眼。'));root.append(el('p','FlightSafety 有持久竞争优势，同时需要持续投资设备。资本需求高，不能单独证明没有护城河；它会影响增长之后，有多少现金能供所有者支配。'));root.append(el('p','这是根据案例预先整理的解释。进一步可以问：新增投入带来的回报是否足够好？'));const b=el('button','再看 FlightSafety 的依据 ↗');b.onclick=()=>openSource(2,'FlightSafety 的资本需求是否否定了它的竞争优势？');root.append(b);}
document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{state.choice=b.dataset.choice;persist();choice();});choice();$('note').value=state.draft;renderEntries();
$('note').oninput=()=>{state.draft=$('note').value;if(persist())$('note-status').textContent='草稿已保存在此浏览器。想保留一次判断时，点击“留下一句理解”。';};
$('note-form').onsubmit=e=>{e.preventDefault();if(!addEntry(state,$('note').value,new Date().toISOString())){$('note-status').textContent='可以写一句再保存，也可以直接跳过。';return;}if(persist())$('note-status').textContent='已留下这次理解。以后修改再保存，会保留之前的记录。仅保存在此浏览器。';renderEntries();};
$('export-note').onclick=()=>{if(!state.entries.length&&!state.draft.trim()){$('note-status').textContent='还没有文字记录。你可以先留下一句理解。';return;}const url=URL.createObjectURL(new Blob([exportRecord(state)],{type:'text/markdown;charset=utf-8'}));const a=el('a');a.href=url;a.download='复利国-喜诗糖果判断记录.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
let sourcesPromise,openRevision=0;function showSource(source,focus){const dialog=$('source-dialog');if(!dialog.open)dialog.showModal();$('source-title').textContent=source.title||source.label||'原文依据';SourceReader.show($('reader'),{...source,focus},'cn');}
async function openSource(index,focus){const rev=++openRevision;const dialog=$('source-dialog');if(!dialog.open)dialog.showModal();$('source-title').textContent='巴菲特 2007 年股东信';$('reader').textContent='正在打开原文…';try{if(!sourcesPromise)sourcesPromise=fetch('/static/moat-sources.json?v=1').then(r=>{if(!r.ok)throw Error();return r.json();}).catch(e=>{sourcesPromise=null;throw e;});const sources=await sourcesPromise;if(rev===openRevision&&dialog.open)showSource(sources[index],focus);}catch(e){if(rev===openRevision)$('reader').textContent='原文暂时未能加载，请关闭后重试，或查看文章末尾的公开信原件。';}}
$('source-dialog').addEventListener('close',()=>{openRevision++;});$('close-source').onclick=()=>$('source-dialog').close();document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>openSource(Number(b.dataset.source),b.dataset.focus));
function renderAnswer(root,text,sources,focus){root.replaceChildren();for(const line of text.split('\n')){if(!line.trim())continue;const heading=/^#{1,4}\s/.test(line);const p=el(heading?'h3':'p');for(const part of line.replace(/^#{1,4}\s/,'').split(/(\[来源\d+\]|\*\*[^*]+\*\*)/g)){const match=/^\[来源(\d+)\]$/.exec(part);if(match&&sources[Number(match[1])-1]){const b=el('button',part);b.className='citation';b.setAttribute('aria-label','打开'+part);b.onclick=()=>showSource(sources[Number(match[1])-1],focus);p.append(b);}else if(part.startsWith('**')&&part.endsWith('**'))p.append(el('strong',part.slice(2,-2)));else p.append(document.createTextNode(part));}root.append(p);}if(sources.length){const details=el('details'),summary=el('summary','核对本次回答的来源（'+sources.length+'）');details.append(summary);sources.forEach((s,i)=>{const p=el('p'),b=el('button',`[来源${i+1}] ${s.title||s.label||s.source_file||'原文'}`);b.onclick=()=>showSource(s,focus);p.append(b);details.append(p);});root.append(details);}}
let busy=false,controller=null,history=[];$('stop').onclick=()=>controller?.abort();
$('ask-form').onsubmit=async e=>{e.preventDefault();const question=$('ask').value.trim();if(busy)return;if(!question){$('ask-status').textContent='写下一个想继续弄懂的问题即可。';$('ask').focus();return;}busy=true;$('ask-submit').disabled=true;$('stop').hidden=false;$('ask-status').textContent='正在结合案例查找原典，回答会逐步出现…';controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),90000);const card=el('article');card.className='answer';card.append(el('h3','你问：'+question));const body=el('div');card.append(body);$('conversation').append(card);let text='',sources=[],finished=false;
const query='我正在阅读喜诗糖果与FlightSafety的对照，主题是持久竞争优势与增长的资本需求。对于“增长需要购买昂贵设备是否意味着没有护城河”，我的选择是“'+(labels[state.choice]||'尚未选择')+'”。我的问题：'+question+'。请结合原典简洁解释，区分证据与推断，最后只给一个值得继续思考的问题。';
try{const res=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,history:history.slice(-8)}),signal:controller.signal});if(!res.ok||!res.body)throw Error('service');for await(const event of events(res.body)){if(event.type==='error')throw Error('service');if(event.type==='sources')sources=event.sources||[];if(event.type==='token'){text+=event.text||'';body.textContent=text.split('<follow')[0];body.style.whiteSpace='pre-wrap';$('ask-status').textContent='正在回答…';}if(event.type==='done'){if(!event.final_answer?.trim())throw Error('empty');sources=event.sources||sources;body.style.whiteSpace='';renderAnswer(body,event.final_answer,sources,question);history.push({role:'user',content:query},{role:'assistant',content:event.final_answer});finished=true;}}if(!finished)throw Error('incomplete');$('ask-status').textContent='回答已完成。可打开引用核对，也可以继续追问。';$('ask').value='';}catch(error){$('ask-status').textContent=error.name==='AbortError'?'回答已停止或等待超时。问题仍保留，可重新提交。':'本次回答未完成，问题仍保留，请稍后重试。';card.append(el('small','本次回答未完成；上方可能仅为部分内容。'));}finally{clearTimeout(timeout);busy=false;controller=null;$('ask-submit').disabled=false;$('stop').hidden=true;}}
})(typeof window==='undefined'?globalThis:window);
